### ISSUE TITLE
RoadMap for Spring Sync

### ISSUE THREAD

**Issue by divyakumarjain** [spring-projects/spring-sync#19]
Would like to know road map for Spring Sync, The concept is good and use cases are large with emergence of Client side MVC frames.

But seem like project is not active as it should be. Would like to know should I plan to use Spring Sync in one of the project.

**Comment by cforce** [comment]
project seems to be dead.

**Comment by gregturn** [comment]
As noted on the README, it's in incubation and under evaluation.

**Comment by cforce** [comment]
this info is about 1 year ago..and no chechin since 2 years.. defacto dead..
